services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000
    # depends_on:
    #   - database

  frontend:
    image: node:22
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    volumes:
      - ./frontend/app:/app
    ports:
      - 3000:3000